spring:
  profiles:
    active: develop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/{teannt-id}/v2.0
      client:
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/{teannt-id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/{teannt-id}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/{teannt-id}/discovery/v2.0/keys
        registration:
          graph:
            provider: microsoft
            client-id: {client-id}
            client-secret: {client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/'
            user-name-attribute-name: upn
            scope:
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Directory.Read.All